### ISSUE TITLE
Interpolation deprecation warning

### ISSUE THREAD

**Issue by dsandstrom** [zurb/foundation-rails#246]
```
DEPRECATION WARNING on line 33 of /usr/local/Cellar/rbenv/1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/foundation-rails-6.4.1.2/vendor/assets/scss/xy-grid/_gutters.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes

  unquote("#{$operator}#{$gutter}")

You can use the sass-convert command to automatically fix most cases.

DEPRECATION WARNING on line 42 of /usr/local/Cellar/rbenv/1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/foundation-rails-6.4.1.2/vendor/assets/scss/xy-grid/_gutters.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{$operator}#{$gutter}")

You can use the sass-convert command to automatically fix most cases.
```

It appears to have been fixed upstream https://github.com/zurb/foundation-sites/blob/eaa79c89a8c5dc89f8fa1e6916ce5dea6cc55866/scss/xy-grid/_gutters.scss#L33 .

**Comment by weiserma** [comment]
When will this be incorporated into the gem?

**Comment by ncoden** [comment]
This was fixed in https://github.com/zurb/foundation-sites/pull/10550 and released in `v6.4.4-rc1`.

See: https://github.com/zurb/foundation-rails/pull/252

**Comment by cooperka** [comment]
For anyone else still hanging on to Foundation 5, here's the latest v5 fork with the same fix as above: https://github.com/bobmccurdy1/foundation-rails/commits/master

To use it, you can put this in your Gemfile: `gem "foundation-rails", github: "bobmccurdy1/foundation-rails", branch: "master"`
